# Generated by Django 3.0.8 on 2020-07-18 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FDT_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=50)),
                ('loginTime', models.DateField(verbose_name='last login time')),
                ('loginIp', models.CharField(max_length=20)),
                ('loginAddress', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FDT_UserOpHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_dingtou.FDT_User')),
            ],
        ),
        migrations.CreateModel(
            name='FDT_User_Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundcode', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_dingtou.FDT_User')),
            ],
        ),
        migrations.CreateModel(
            name='FDT_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fund_dingtou.FDT_User')),
            ],
        ),
    ]
